Correct Section 1.13 Simple
stan-dev/docs pull request #290
Opened 2020-11-20 09:15 UTC by abeeisnotabug

#### Summary
Correct the transpose operations in the "Optimization through Cholesky Factorization" section. Please see advanced PR for more concise rework.

2020-11-20 14:03 UTC, bbbales2 requested changes
One simplification, thanks for finding this!

2020-11-20 14:03 UTC, bbbales2 commented on src/stan-users-guide/regression.Rmd
> +  = diag_post_multiply(L_Omega', tau)' * diag_post_multiply(L_Omega', tau)
`diag_pre_multiply(tau, L_Omega) * diag_post_multiply(L_Omega', tau)`

2020-12-01 13:16 UTC, bbbales2 commented
@abeeisnotabug we can close this now right?

2020-12-02 23:59 UTC, abeeisnotabug commented
> @abeeisnotabug we can close this now right?

Yes! Thank you engaging with all this!

2020-12-02 23:59 UTC, closed without merging