Issue 185 - GP Docs
stan-dev/docs pull request #293
Opened 2020-12-03 10:34 UTC by drezap

#### Submission Checklist

- [x] Builds locally 
- [x] Declare copyright holder and open-source license: see below

#### Summary

Just wondering if anyone had any comments before I move further.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Andre Zapico

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2020-12-03 17:08 UTC, jgabry commented
Thanks Andre. Tagging @rtrangucci and @avehtari who know more about GPs than I do. Rob or Aki if you don't have time to look at this can you recommend someone else who would be able to look at GP doc?

2020-12-07 15:00 UTC, avehtari commented
I'll check this this week

2020-12-11 19:44 UTC, avehtari requested changes

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +f(x_i) = sin(\frac{x_i}{2\pi}) + sin(\frac{.7 x_i}{2\pi})
I would the function as 
f(x) = sin(\frac{x}{2\pi}) + sin(\frac{.7 x}{2\pi})

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +and the observed data, with noise, is then:
and the observed data (y_1, ..., y_N), with noise, is then:

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +The function $f(x_i)$, without noise for $x=1,2,3,...,100$, looks like this
The function $f(x)$,

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Previously, we have only considered a noiseless gaussian process. That is, we've fixed $\delta$ to a small constant not less than zero. In gaussian process regression, an identically distributed inde
gaussian -> Gaussian
gaussian -> Gaussian
"In gaussian process regression, an identically distributed independent noise is equivalent to having $\delta$, for example, be normally distributed."
-> Here we assume that noise standard deviation $\delta$ is unknown with, for example, half-normal prior distribution.

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +In Stan, we can simulate a GP model with noise by declaring $\delta$ as a parameter and setting $\delta$ to be normally distributed, as above. For a Gaussian likelihood, function, a Stan snippet woul
"setting $\delta$ to be normally distributed, as above."
-> defining a prior on $\delta$.
"For a Gaussian likelihood, function, "
-> for normal observation model,

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +We set the prior for the noise more diffuse, and then the noise for the Gaussian Process is estimated from the data. Beware, however, since the hyper prior is more diffuse and the true noise is likel
As delta is scalar, there is no real hierarchy here. This is just a wider prior on delta. Hierachical model would make sense only if there would be many deltas. This section can be removed.

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Currently, Stan supports several build in covariance functions (kernels). These are the squared exponential, also known as the radial basis function or the gaussian kernel, a dot product or linear co
"squared exponential, also known as the radial basis function or the gaussian kernel"
->
exponentiated quadratic
(the other names are mentioned later)

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +And then we add noise and sample from a multivariate gaussian distribution using cholesky decomposition:
"add noise"
->  add noise standard deviation
gaussian -> Gaussian
cholesky -> Cholesky

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Fixing the bias parameter, we can generate samples from the linear kernel (left) and the linear kernel fitting a linear function:
"we can generate samples from the linear kernel (left) and the linear kernel fitting a linear function:"
-> we can generate samples from a GP with the linear covariance function (left) and a GP with linear covariance function fitting ???: (I don't understand the end and graphic is missing).

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +The periodic covariance function is used to interpolate periodic trends in data, and can be used to model anything that follows a periodic pattern, such as seasonal trends or oscillations in time. Th
"The periodic covariance function is used to interpolate periodic trends in data, and can be used to model anything that follows a periodic pattern, such as seasonal trends or oscillations in time."
-> The periodic covariance function is used to model periodic trends in data, such as seasonal patterns or oscillations in time.

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +K(t, t' \mid \sigma, l, \rho) = \sigma^2 \exp\left(\dfrac{-2 sin^2(\pi(t - t')/ \rho)}{2 l^2}\right).
See the earlier comment about the notation

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +K(x, x' \mid \sigma, l) = \sigma_0^2 + (x', x)
See the earlier comment about the notation

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +The dot product kernel, or linear kernel, is analogous to a Bayesian linear regression with a normal(0, 1) prior on regression coefficients. This can be combined with other covariance functions to in
dot product kernel -> dot product covariance function
"with a normal(0, 1)"
don't we have magnitude parameter for it?
"to interpolate linear trends in data"
-> to include an additive linear component to the model.

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Here's what a Gaussian Process regression fit looks like when the true noise standard deviation is 1:
And what is the standard deviation of the fit?

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Unfortunately, this is not always the case, and instead, we could have noise for which that standard deviation is not exactly 1. Here's an example of a fit on simulated data when the noise model is m
"Unfortunately, this is not always the case, and instead, we could have noise for which that standard deviation is not exactly "
-> remove whole sentence
" Here's an example of a fit on simulated data when the noise model is misspecified:"
misspecified in what way?

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +### The Squared Exponential
exponentiated quadratic

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +A common choice for a covariance function is the Squared Exponential covariance function. This is also known as the Radial Basis Function or the Gaussian kernel, due to the fact that its function res
"Squared Exponential"
-> exponentiated quadratic
"the Radial Basis Function or the Gaussian kernel"
-> squared exponential, the radial basis function or the Gaussian kernel
"gaussian"
-> Gaussian
"is as follows"
-> is

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +K(x, x' \mid \sigma, l) = \sigma^2 \exp\left(-\dfrac{||x - x'||_2^2}{2 l^2}\right).
The notation doesn't match the notation in section 10.1

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +for $\sigma,l \geq 0$, where $||\cdot||_2^2$ is the squared l-2 norm, and $x$ and $x'$ are observations of design matrix $X$. The $K_{i,j}$ will then be the covariance computed between rows $i$ and $
the notation in section 10.1 is better as it connects i and j to the function

"Here's what draws from the squared exponential kernel look like
-> Here's how the draws from a GP with exponentiated quadratic covariance function look like

"fixed hyper priors"
or fixed values?

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +We can sample from a multivariate gaussian distribution in Stan by first instantiating a covariance matrix, for example for `vector[D] x[N]`, and parameters `real<lower=0> sigma` and `real<lower=0> l
gaussian -> Gaussian
for -> given

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Where since $\eta \sim normal(0, 1)$, $f$ is distributed multivariate normal.
"$f$ is distributed multivariate normal."
-> $f$ has a multivariate normal prior with covariance matrix $K$.

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +We can implement a gaussian process regression model with a Squared Exponential kernel, along with the posterior predictive for the regression model as follows:
gaussian -> Gaussian
Squared Exponentialkernel -> exponentiated quadratic covariance function
predictive -> prediction

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +We can define a dot product covariance function almost identicle to defining the squared exponential covariance function, instead as `gp_dot_prod_cov` with a constant parameter $\sigma_0$, for traini
identicle -> identical
squared exponential -> exponentiated quadratic
"for training data"
-> for predictor matrix

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +The code for fitting a linear model in Stan with a Gaussian Process is almost indenticle to that of fitting a GP regression with a squared exponential kernel, but instead replacing every instance of
Process -> process
identicle -> identical
squared exponential kernel -> exponentiated quadratic covariance function

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +For $\sigma > 0$, $l > 0$ , and $\rho > 0$. We use $t$ since it is common to see the periodic covariance function used in time series application. Typically, $t$ will denote points measured in time.
"It is common to rescale $\mathbf{t}$ so that the integral to approximate is compatible with Stan's sampler."
what does this mean?

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +K(t, t' \mid \sigma, l, \rho) = \sigma^2 \exp\left(\dfrac{-2 sin^2(\pi(s(t) - s(t'))/ \rho)}{2 l^2}\right).
See the comment about the notation earlier

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Calls of the periodic covariance function for a training covariance matrix and cross covariance matrix in Stan, respectively, look like
a training covariance matrix -> a covariance matrix

2020-12-11 19:44 UTC, avehtari commented on src/stan-users-guide/gaussian-processes.Rmd
> +Here's an example of the periodic function interpolating a simulated sine wave with gaussian noise:
interpolating -> fitted to a 
gaussian -> Gaussian

2022-04-06 16:04 UTC, bob-carpenter commented
this one never got update after change requests, so I'm going to close.  @drezap:  if you do want to address the comments, just reopen the issue.  I'm trying to close all the outdated issues.

2022-04-06 16:04 UTC, closed without merging

2022-04-06 17:40 UTC, drezap commented
Hi,

I can't work on this unless I'm being compensated.

Thank you.

On Wed, Apr 6, 2022 at 12:04 PM Bob Carpenter ***@***.***>
wrote:

> Closed #293 <https://github.com/stan-dev/docs/pull/293>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stan-dev/docs/pull/293#event-6381424345>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACY543HNGAP2R4W3L4LHECTVDWYZJANCNFSM4ULY3SKQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>