Update decision-analysis.Rmd
stan-dev/docs pull request #345
Opened 2021-03-14 05:27 UTC by hyunjimoon

Considering the dimension and the fact that d[N] was not used in the original code, how is this revised version? @bob-carpenter

2021-03-15 18:12 UTC, bbbales2 requested changes
Good catch. Your change looks right but can be vectorized.

2021-03-15 18:12 UTC, bbbales2 commented on src/stan-users-guide/decision-analysis.Rmd
> +  }
This can be vectorized like:

```
t ~ lognormal(mu[d], sigma[d]);
c ~ lognormal(nu[d], tau[d]);
```

2021-03-15 22:41 UTC, hyunjimoon commented on src/stan-users-guide/decision-analysis.Rmd
> +  }
I agree!

2021-03-24 13:42 UTC, bbbales2 approved these changes

2021-03-24 13:43 UTC, bbbales2 commented
@hyunjimoon I vectorized the model and fixed another typo. Hit merge if it looks good to you.

2021-03-24 23:36 UTC, hyunjimoon commented
I have reviewed the changes and it looks good to me. Unfortunately I don't have the writing access to this repository. Could you hit merge please? Thanks! @bbbales2

2021-03-24 23:40 UTC, merged