Make notation for Pr consistent
stan-dev/docs pull request #627
Opened 2023-03-23 19:41 UTC by WardBrian

#### Submission Checklist

- [x] Builds locally 
- [x] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #602

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2023-03-23 20:43 UTC, bob-carpenter requested changes
Two things.

1.  The definition of `\Pr` should be `\textrm{Pr}`.  If not, please make it that.
2.  We probably want to go with the `Pr[...]` form with square brackets.<sup>*</sup>  So I marked the one with parens that I saw.

<hr />
<sup>*</sup> The convention for round vs. square brackets (imported from physics, I believe) is that higher-order functions that apply to other functions use square brackets.  That's why E[] and Pr[] use square brackets, but p() uses round brackets---the former take random variables as arguments (which are functions), whereas p() just takes primitive arguments.

2023-03-23 20:43 UTC, bob-carpenter commented on src/stan-users-guide/finite-mixtures.Rmd
> +\Pr\left(z_n = k \mid y_n, \mu, \sigma, \lambda \right)
'(' to '[' and similarly for closing parens.  If you are using `\left[`, then it should have a bit of negative space, `\Pr\!\left[` in order to not leave too much space between the "Pr" and the "[".   The alternative is to make \Pr take an argument and put it in the brackets, i.e.,

```latex
\newcommand{\Pr}[1]{\textrm{Pr}\!\left[ #1 \right]}
```

2023-03-23 20:43 UTC, bob-carpenter commented on src/stan-users-guide/finite-mixtures.Rmd
> +\log\,&\Pr\left(z_n = k \mid y_n, \mu, \sigma, \lambda\right) \\
round to square

2023-03-23 20:50 UTC, WardBrian commented
The original issue was opened because `\Pr` is built in: $\Pr$ 

It looks identical to `\mathrm{Pr}` in practice: $\mathrm{Pr}$

2023-03-29 18:31 UTC, WardBrian commented
@bob-carpenter mind giving this another look?

2023-09-30 13:54 UTC, bob-carpenter approved these changes
Thanks.  Looks good.

2023-09-30 13:54 UTC, merged