survival model chapter with refs
stan-dev/docs pull request #695
Opened 2024-01-02 22:13 UTC by bob-carpenter

#### Submission Checklist

- [x] Builds locally 
- [x] New functions marked with `` `r since("VERSION")` ``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add a chapter on parametric and non-parametric survival models with refs.  I've tested that all the code works with Python simulations.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2024-01-07 18:57 UTC, mitzimorris requested changes
this is great.
please fix '\[', level 3 headings, and type.
comments are places where a little more exposition might help.

2024-01-07 18:57 UTC, mitzimorris commented on src/stan-users-guide/survival.Rmd
> +same survival time.  The number of elements with surival time `j` is thus
^surival^survival^

2024-01-07 18:57 UTC, mitzimorris commented on src/stan-users-guide/survival.Rmd
> +
discuss why not generative w/r/t hazard function but is generative w/r/t ordering.

2024-01-08 16:47 UTC, bob-carpenter commented
I wasn't entirely clear on what this meant:

> please fix '[', level 3 headings, and type.

I think the first is referring to replacing `\[` with `\begin{equation*}`, which I did.

I think the second is referring to adding `{-}`, which I did.

I couldn't figure out what the third request ("type") meant.

2024-01-08 16:49 UTC, bob-carpenter commented on src/stan-users-guide/survival.Rmd
> +a group of subjects that is
Thanks---I was struggling with this throughout and fixed as requested.

2024-01-08 16:52 UTC, bob-carpenter commented on src/stan-users-guide/survival.Rmd
> +where $F_T$ is the cumulative distribution function (cdf) of survival
F_X is standard notation for the cdf of the random variable X.  I defined it again locally in the doc.

2024-01-08 19:00 UTC, mitzimorris commented on src/stan-users-guide/survival.Rmd
> +failure because the baseline hazard function $h_0(t)$ is unmodeled; if
"because". .... "because". - something's redundant here

2024-01-08 19:01 UTC, mitzimorris approved these changes
looks great!
one changes needs further editing - then good to go.

2024-01-16 17:48 UTC, merged