Edit to macOS C++ install docs
stan-dev/docs pull request #817
Opened 2024-09-24 14:38 UTC by JoFrhwld

#### Submission Checklist

- [x] Builds locally
- [x] New functions marked with `` <<{ since VERSION }>>``
- [x] Declare copyright holder and open-source license: see below

#### Summary

As currently written, the C++ toolchain documentation for macOS sends users first to install Xcode from the app store. I've placed a check on whether clang++ and make are installed above that. I've also replaced the instructions to install Xcode from the app store with just the `xcode-select --install` instruction. My reasoning for this is:

##### Adding a check first

- It makes the MacOS instructions more parallel with the Linux and Windows instructions, which also have a checking step before an installation step.
- Some people who are less familiar with these tools may, nevertheless, have installed the Xcode command line tools previously, but don't necessarily remember that they have done so.
- The documented experience of what options are available, and what will happen, will be different depending on whether or not command line tools have already been installed.

##### Removing Xcode app install
The documented steps for installing command line tools through the Xcode app appear to be outdated at least by Xcode v15.4. There is no `Xcode>Preferences` menu, and under `Xcode>Settings`, there is no Downloads tab. In fact, poking around, it's not entirely clear to me _how_ to install command line tools within the Xcode app.

Installing command line tools with `xcode-select --install` still works, and involves fewer steps.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Josef Fruehwald

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2024-09-24 14:42 UTC, WardBrian commented
Thank you for updating these! I think it is worth keeping a link to https://developer.apple.com/xcode/ if people want to read more

2024-09-24 15:46 UTC, mitzimorris requested changes
~~why delete instructions on how to get Xcode from Apple?~~
nevermind - agree w/ your reasoning and Brian's comment.

one further suggested addition for Mac users:  don't use gnu++ via homebrew:

"We don't recommend trying to use the GNU C++ compiler, available via Homebrew,
based on the number of reports of installation difficulties from Mac users on GitHub
as well as the Stan forums."

2024-09-24 16:34 UTC, bob-carpenter commented
Thanks for updating, @JoFrhwld.  I was coming here to add this from Apple:

> You can install the Command Line Tools package by running the xcode-select --install command. Note: macOS comes bundled with xcode-select , a command-line tool that is installed in /usr/bin . It allows you to manage the active developer directory for Xcode and other BSD development tools.

From:  https://developer.apple.com/library/archive/technotes/tn2339/_index.html

2024-09-24 18:46 UTC, JoFrhwld commented
I've added both @mitzimorris' admonition against the homebrew version, as well restored a link to the Xcode site as suggested by @WardBrian. Thanks for finding the reference to `xcode-select`'s general availability, @bob-carpenter

2024-10-03 20:09 UTC, mitzimorris approved these changes
many thanks for this cleanup!

2024-10-03 20:09 UTC, merged