Start documentation of sum_to_zero_vector
stan-dev/docs pull request #818
Opened 2024-09-26 14:46 UTC by WardBrian

#### Submission Checklist

- [x] Builds locally
- [x] New functions marked with `` <<{ since VERSION }>>``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #804.

I think I need some help from @spinkney @bob-carpenter filling out the documentation of the specific transform, see the two "TODO:" lines in `transforms.qmd`

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2024-09-30 19:25 UTC, spinkney commented
I'll try and take a look this week

2024-09-30 20:19 UTC, bob-carpenter commented
I can take a shot at this, @spinkney.  I think the definition is clear enough.

2024-10-01 20:23 UTC, bob-carpenter commented
I have most of this written up and just have to double check.  I should be able to push the doc tomorrow (Wednesday).  I'm just transating from the code.  It's really nice that there's no Jacobian adjustment.

2024-10-04 21:25 UTC, bob-carpenter commented
I wrote out the math for the transform.  It'd be great if @spinkney could review, though I'm pretty sure it at least matches the code as is (perhaps modulo a +1 or -1 on indexing, but I triple-checked all that, too).

2024-10-30 16:38 UTC, WardBrian commented
@spinkney do you think you will have a chance to look at this?

2024-10-31 00:18 UTC, spinkney commented
> @spinkney do you think you will have a chance to look at this?

When is the deadline?

2024-10-31 00:30 UTC, WardBrian commented
The 11th, unless we end up delaying the release again

2024-11-02 11:38 UTC, spinkney commented
I will either finish this before 11/9 or let you know I won't be able to make the deadline.

2024-11-04 16:50 UTC, bob-carpenter commented
It's very minimal and it's all written---just needs someone to verify it's OK.

2024-11-06 15:02 UTC, spinkney commented
> It's very minimal and it's all written---just needs someone to verify it's OK.

I'm on vacation and coming back tomorrow. I'll take a look then.

2024-11-09 19:24 UTC, spinkney commented
I'll have time to look at it this weekend/monday

2024-11-15 12:36 UTC, spinkney commented
looking at this later this morning. Sorry about the delay!

2024-11-15 15:36 UTC, spinkney requested changes
Added a bunch of details. We may even want to write out the Householder stuff. Adrian wrote about it here https://github.com/pyro-ppl/numpyro/pull/1751#issuecomment-1980569811. I took most of the derivation from something I posted on discourse at https://discourse.mc-stan.org/t/new-stan-data-type-zero-sum-vector/26215/11?u=spinkney.

2024-11-15 16:31 UTC, bob-carpenter commented on src/reference-manual/transforms.qmd
> +For the transform, Stan uses the first part of an isometric log ratio
I wouldn't say "just a reference manual".  We want to get the details of the transformation we're using right.  This isn't a research paper, though, so we don't need to say why we're using this, though we can link to a paper or to Adrian's discussion online.  External links are challenging to maintain, so use sparingly.

We can mention the link to Householder, but I wouldn't go through this whole discussion in the transforms chapter of the Stan reference manual.

2024-11-15 16:35 UTC, bob-carpenter commented on src/reference-manual/transforms.qmd
> +For the transform, Stan uses the first part of an isometric log ratio
I'm not sure how to update.  Do you want to take a stab at just updating it?  If not, if you can write here what you think I should add, I'll add it.

2024-11-15 20:14 UTC, bob-carpenter commented
I added a short note and citation in the reference manual and then just used your text in full in the user's guide.  I got rid of the simplex suggestion we had, but left the soft-centering.

2024-11-15 21:00 UTC, spinkney approved these changes
Just the one double space and the rest looks good!

2024-11-15 21:12 UTC, bob-carpenter commented on src/reference-manual/types.qmd
> +vectors and vice-versa.  Zero sum  vector variables, like other constrained
Fixed.  The spaces don't matter for rendering.

2024-11-15 21:12 UTC, bob-carpenter commented
@spinkney I think this is then ready for final review.  I removed the extra space.

2024-11-15 21:41 UTC, merged

2024-11-26 06:03 UTC, lingium commented on src/reference-manual/transforms.qmd
> +For the transform, Stan uses the first part of an isometric log ratio
I think your description of  "zero correlation" might be wrong. Think about a vector that sum to zero, if one element becomes larger, then other elements `must` be smaller, right? So as long as they sum to zero, they are all negativly correlated.

2024-11-26 10:56 UTC, spinkney commented
Absolutely! I don't know why I keep saying correlation. The correct thing
here is that the transform we have results in equal variances. We need to
add in a zero_sum_normal which results in the zero sum elements having mean
0 and stdev equal to the user specified value which will be the same as
N(0, val). I'll put a fix in for the docs later today, unless someone else
gets to it before.

On Tue, Nov 26, 2024, 1:03 AM Zhi Ling ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/reference-manual/transforms.qmd
> <https://github.com/stan-dev/docs/pull/818#discussion_r1857847885>:
>
> > @@ -462,6 +462,83 @@ p_Y(y)
>  $$
>
>
> +
> +## Zero sum vector
> +
> +Vectors that are constrained to sum to zero are useful for, among
> +other things, additive varying effects, such as varying slopes or
> +intercepts in a regression model (e.g., for income deciles).
> +
> +A zero sum $K$-vector $x \in \mathbb{R}^K$ satisfies the constraint
> +$$
> +\sum_{k=1}^K x_k = 0.
> +$$
> +
> +For the transform, Stan uses the first part of an isometric log ratio
>
> I think your description of "zero correlation" might be wrong. Think about
> a vector that sum to zero, if one element becomes larger, then other
> elements must be smaller, right? So as long as they sum to zero, they are
> all negativly correlated.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stan-dev/docs/pull/818#discussion_r1857847885>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFU3D6OG4WYXV4VGSUXYQ7T2CQFMRAVCNFSM6AAAAABO5GM2MWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINRQGQ2DEMZSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-26 19:30 UTC, bob-carpenter commented
Also, when discussing correlation, there's the issue of whether we're talking about the `N - 1` unconstrained parameters or the `N` constrained parameters.

2024-11-27 10:58 UTC, lingium commented
yeah, unconstrained parameters are independent, and constrained parameters are negatively (but equally, guess @spinkney also would like to mentin this) correlated