Add section about Pathfinder diagnostic and using for inits
stan-dev/docs pull request #833
Opened 2024-11-15 16:36 UTC by avehtari

#### Summary

Related to #751 and recent discussion about using Pathfinder for inits in https://discourse.mc-stan.org/t/using-pathfinder-to-initalize-sampling/37221

I now just added brief sections on Pareto-k diagnostic and using Pathfinder for inits. It would be good to add much description about the Pathfinder overall.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2024-11-15 16:42 UTC, bob-carpenter requested changes
Thanks for writing this up.  Just some small clarifying comments and typos and references.

2024-11-15 16:42 UTC, bob-carpenter commented on src/reference-manual/pathfinder.qmd
> +the approximation and using Pareto-$\hat{k}$ diagnostic (Vehtari et al., 2024) to assess whether these ratios can
We should use actual references here like "@zhang_pathfinder:2022"

2024-11-15 16:42 UTC, bob-carpenter commented on src/reference-manual/pathfinder.qmd
> +be used to improve the approximation via resmapling. /, the
resmapling is misspelled.

I don't know what the / is doing here---should this be a different character?

2024-11-15 16:42 UTC, bob-carpenter commented on src/reference-manual/pathfinder.qmd
> +there is still need to further diagnose importance sampling estimates by taking into account also the expetant
I don't know the word "expetant"---looks like it's Latin.  Can we just write this in English?

2024-11-15 16:42 UTC, bob-carpenter commented on src/reference-manual/pathfinder.qmd
> +parts of Bayesian workflow (Gelman et al, 2020).
All of these should get turned into citations.

2024-11-16 15:08 UTC, avehtari commented
I fixed references and several typos

2024-11-18 17:18 UTC, merged

2024-11-18 17:19 UTC, bob-carpenter commented
P.S.  I fixed the merge conflict in the .bib file.  Hope I didn't break anything in the process.