Issue/838 hmm
stan-dev/docs pull request #840
Opened 2024-12-06 21:35 UTC by charlesm93

#### Submission Checklist

- [x] Builds locally
- [x] New functions marked with `` <<{ since VERSION }>>``
- [x] Declare copyright holder and open-source license: see below

#### Summary

Addresses issue #838 and updates user-doc on HMMs.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Charles Margossian, Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/)

2024-12-06 22:13 UTC, bob-carpenter commented
I took a look through this and while I'm in favor of minimal examples, this one's a bit too minimal.  I would really like to see the model laid out in more detail than the conditional distributions.  Here are some concrete suggestions:

1.  Use `z` for latent discrete parameters.  We already use `x` for covariates, so it's confusing to use `x`.  I've used `z` elsewhere in the user manual for this in the latent discrete parameter chapter.

2. Define the complete data likelihood $p(y, z | \phi) = p(z \mid \phi) \cdot p(y \mid z, \phi)$ and then the marginalization $p(y \mid \phi)$ that we actually fit.

3.  Mention that $\phi$ is actually several parameters.

4.  I find the constrained version of the transition matrix where you insert zeros makes this first example too challenging.  If you want to discuss that case, I'd suggest another section after this one where you talk about imposing structural zeros.  Otherwise it makes the simple case seem too complicated.  And then you can just define

```stan
array[3] simplex[3] gamma_arr;

matrix[3, 3] gamma;
for (n in 1:3) gamma[n] = gamma_arr[n];
```

5.  For the doc, those `mu` and `sigma` are not just the measurement model---that's all the error terms.

6.  Wherever you have repetition, use loops.  It's less error prone and more clear that it's a homogeneous operation:

```stan
for (n in 1:N) {
  for (k in 1:3) {
    log_omega[k, n] = normal_lpdf(y[n] | mu[k], sigma);
  }
}
```

7. Given that you're tying the parameter `sigma` across outputs, you need to mention that.  I'd recommend just keeping this simple with a vector of `sigma` values.

8.  You can't just say "computes the relevant log marginal distribution"---you have to say what that is.  I don't mean including the marginalization algorithm, I just mean as I wrote it above.

9.  For more details, since -> For more details, see.   Also, I wouldn't say "corresponding case study", I'd just say it's a case study on HMMs.  And then you should put it in the bibtex file and cite it properly with reference to Ben (the author).  And you should cite that you "borrowed" the example from Ben Bales's case study.

2025-01-15 10:46 UTC, charlesm93 commented
I'm rewriting the code to make the transition matrix less constrained (per comment 4) and I wanted to check: we don't have a stochastic matrix type, right?

2025-01-15 13:36 UTC, WardBrian commented
We have row and column but not double yet https://mc-stan.org/docs/reference-manual/types.html#stochastic-matrices

2025-03-14 18:27 UTC, charlesm93 commented
@bob-carpenter I implemented your feedback.

Some questions:

5. What exactly is the difference between a measurement and an error model? I'm ok to use either term, and I know they have different conceptual implication, but I'm wondering if they have a formal definition.

7. I'm keeping `sigma` a scalar. I'm not sure it's simpler conceptually to pass it as a vector.

2025-03-14 20:15 UTC, bob-carpenter commented
For (5), I think the idea's that there are three sources of error:  measurement error, modeling error, and sampling error.  For example, sampling error arises when you subsample a population and use that for estimation.  You get modeling error if you use a linear regression for a relationship that's not linear or use normal errors when the errors are skewed, and so on.  If you're weighing things with a scale and you know the scale's biased to the high side, you can correct that measurement error.  You can explicitly add a measurement error model if you know your measurement model (e.g., gravitational lensing is part of the measurement error model; your work with Bruno et al. on deconvolving galactic dust is part of the measurement model for the CMB, etc.).

2025-03-14 20:42 UTC, bob-carpenter requested changes
There's a ton of little things to fix, but nothing major.

2025-03-14 20:42 UTC, bob-carpenter commented on src/functions-reference/functions_index.qmd
> +<a id='beta_neg_binomial_cdf' href='#beta_neg_binomial_cdf' class='anchored unlink'>**beta_neg_binomial_cdf**:</a>
Why is this PR touching negative binomial?  Are you up to date with the main branch?

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +When $z_{1:N}$ is continuous, the user can explicitly encode these distributions
Isn't `z_{1:N}` a subset of $\\{ 1, ..., K \\}^N$ when $K$ is the number of states?  I don't think it can be continuous.  

Did you perhaps mean to say that the output $y_1, \ldots, y_T$ can be continuous?  It can also be mixed discrete and continuous, it can be multivariate, etc.---it can really be anything.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +$$
I think you need to mention that this is a right-stochastic matrix, where we now have that data type built in.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> + \rho_k = p(z_0 = k \mid \phi).
I would mention at this point that it is common to take $\rho$ to be the stationary distribution of the HMM.  Many package like movementHMM in R let you set it to the stationary distribution by default.  You can mention that the stationary distribution is the first eigenvector (that's why they called Google's PageRank algorithm, which computed the stationary distribution of their random web walking model using an iterative algorithm, the "billion-dollar eigenvector").  It's the solution for $\pi$ in $\Gamma \cdot \pi = \pi$ for left-stochastic transition matrix $\Gamma$.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +The observations are normally distributed with
`K` is an integer, so I think that should just be $K = 3$.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +The observations are normally distributed with
normally distributed conditioned on the HMM state

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +across all observation.
observation -> observations

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +  array[3] simplex[3] gamma_arr;
Ack.  Does this mean you require an array of simplexes, but our `row_stochastic_matrix` type is a matrix so it can't be used.  If so, that's a real bummer, because nobody will ever use the `row_stochastic_matrix` type!  I guess we didn't think the data types through with @SteveBronder.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +  simplex[3] rho;
Why are there no more priors on the simplexes?  You should at least mention here that they're getting default uniform priors over the simplexes.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +The last function `hmm_marginal` takes in all the ingredients of the HMM,
Eliminate the comma---English doesn't use commas between conjunctions unless there are more than two.  So it's just "A and B", but it's either "A, B, and C" (Oxford style) or "A, B and C" (defective American style).

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +a sample from $p(z \mid y, \phi)$.
You don't typically need draws from $z$.  If you do need statistics involving $z$, it's often easier to compute them in expectation (i.e., take advantage of the Rao-Blackwellization you get from marginalizing).  For example, if there are low probability but non-zero $z$, they're very hard to evaluate with sampling.  There are examples in the latent discrete parameters chapter.

You can also use the forward-backward algorithm to work out marginally $p(z_n \mid y)$ and you can use Viterbi with backtracking to find the most probable z given y.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +that is $\text{Pr}(z_n = k \mid \phi, y)$.
Typically this `phi` is marginalized out and we look at  $p(z_n = k | y)$.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +Therefore, `hidden_probs` should NOT be used to obtain posterior samples.
NOT -> *not* (that'll make it italics, which is the standard way to add emphasis to typeset text).

This point is a bit more subtle, though.  You can use this to obtain posterior draws of the marginals $z_n \sim p(z_n \mid y)$, but if you put a sequence of draws from $p(z_1 \mid y), \ldots, p(z_N \mid y)$, you don't get a draw of $p(z \mid y)$.

2025-03-14 20:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +Instead, users should rely on `hmm_latent_rng`.
Although not necessary, it's nice to have examples of how to do that.  Like:

```stan
generated quantities {
   array[N] int<lower=1, upper=K> z = hmm_latent_rng(...fill-in params here to match example...);
}
```

I know this feels obvious, but it can be hard for the users to put the arguments and result types together.

2025-04-16 20:14 UTC, charlesm93 commented on src/functions-reference/functions_index.qmd
> +<a id='beta_neg_binomial_cdf' href='#beta_neg_binomial_cdf' class='anchored unlink'>**beta_neg_binomial_cdf**:</a>
hmmm... that's odd. Let me check.

2025-04-16 20:17 UTC, charlesm93 commented on src/stan-users-guide/time-series.qmd
> +When $z_{1:N}$ is continuous, the user can explicitly encode these distributions
`z_{1:N}` denotes the latent variables. In general, the domain of `z` can be continuous, say $\mathbb R$, or discrete  $\{1, \cdots, K\}^N$.

2025-04-16 20:27 UTC, charlesm93 commented on src/stan-users-guide/time-series.qmd
> +  array[3] simplex[3] gamma_arr;
We wrote the HMM suites before we had stochastic matrices. We can do a PR and change the arguments.

2025-04-16 20:30 UTC, charlesm93 commented on src/stan-users-guide/time-series.qmd
> +The last function `hmm_marginal` takes in all the ingredients of the HMM,
Ok. Although I was under the impression they didn't use the Oxford comma in the UK. I remember noticing this during StanCon in Cambridge and I figured out the Cambridge folks were just taking a piss. But when I asked some of the locals, it turned out they were familiar with the Oxford comma.

2025-04-16 20:32 UTC, charlesm93 commented on src/stan-users-guide/time-series.qmd
> +a sample from $p(z \mid y, \phi)$.
I added "If we desire samples from the posterior distribution of $z$..."

2025-04-16 20:34 UTC, charlesm93 commented on src/stan-users-guide/time-series.qmd
> +that is $\text{Pr}(z_n = k \mid \phi, y)$.
You get $p(z_n = k \mid y)$ by averaging all the MCMC draws. I'll specify this in the doc.

2025-04-16 20:41 UTC, charlesm93 commented on src/functions-reference/functions_index.qmd
> +<a id='beta_neg_binomial_cdf' href='#beta_neg_binomial_cdf' class='anchored unlink'>**beta_neg_binomial_cdf**:</a>
As far as I can tell, I am up to date with the main branch, so I'm not sure how this error occurred. I suppose I could simply delete the extra lines.

2025-04-16 20:41 UTC, charlesm93 commented
@bob-carpenter I completely missed your review. Sorry about that. Hopefully we'll merge this in soon.

2025-08-26 22:42 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +Instead, users should rely on `hmm_latent_rng`.
In the interest of getting this in, I'll just call this resolved.

2025-08-26 22:44 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +  array[3] simplex[3] gamma_arr;
I think that would be good longer term.  Pinging @SteveBronder about that.  But it doesn't need to be done for this doc PR.

2025-08-26 22:46 UTC, bob-carpenter commented on src/stan-users-guide/time-series.qmd
> +When $z_{1:N}$ is continuous, the user can explicitly encode these distributions
I think that's a "yes" :-)

2025-08-26 22:46 UTC, merged